# Aufgabenblatt 8:

## Aufgabe 1: 

Durch die zufälligen Werte in dem Dataframes `data_np` werden die angezeigten Lösungen nicht mit euren Lösungen identisch sein. Die angezeigten Lösungen sollen euch nur einen Indikator anzeigen, was bei den Aufgaben gemacht werden soll.

In [26]:
import pandas as pd
import numpy as np
import random
import string

data_np = {'column_int': np.random.randint(1,10, size=100)
        , 'column_int_1': np.random.randint(1,10, size=100)
        , 'column_float': np.random.uniform(low=-100, high=100, size=(100))
       }

data_np = pd.DataFrame(data_np)
data_np.head()

,column_int,column_int_1,column_float
0,4,6,7.107220
1,5,5,-34.254537
2,9,4,-41.623017
3,1,8,-11.140966
4,2,4,9.046414


- ersetze in dem Dataframes `data_np` in der Column `column_int_1` die Werte `6 und 7`  mit `NaN-Werten`
<br><br>**Tipp** verwende replace und gebe beide Elemente in einer Liste wieder

,column_int,column_int_1,column_float
0,4,NaN,7.107220
1,5,5.0,-34.254537
2,9,4.0,-41.623017
3,1,8.0,-11.140966
4,2,4.0,9.046414
...,...,...,...
95,8,1.0,39.788567
96,4,4.0,-83.671967
97,1,9.0,59.157147
98,1,3.0,2.701248


- bestimme die Grösse (columns und records) von dem Dataframes `data_np`

(100, 3)

- berechne für alle `Column` aus dem Dataframes `data_np` den dazugehörigen mean pro Column

column_int      5.020000
column_int_1    4.237500
column_float   -5.078133
dtype: float64

- berechne nun den mean pro `Row` für den Dataframe `data_np`
- Was muss sich ändern in den Parametern von mean?

0      5.553610
1     -8.084846
2     -9.541006
3     -0.713655
4      5.015471
        ...    
95    16.262856
96   -25.223989
97    23.052382
98     2.233749
99   -15.809550
Length: 100, dtype: float64

- füge dem Dataframe `data_np` eine neue `Column` mir dem Namen `mean_row` hinzu 
- Die Column `mean_row` wird der durchschnitts Wert pro row übergeben

,column_int,column_int_1,column_float,mean_row
0,4,NaN,7.107220,5.553610
1,5,5.0,-34.254537,-8.084846
2,9,4.0,-41.623017,-9.541006
3,1,8.0,-11.140966,-0.713655
4,2,4.0,9.046414,5.015471
...,...,...,...,...
95,8,1.0,39.788567,16.262856
96,4,4.0,-83.671967,-25.223989
97,1,9.0,59.157147,23.052382
98,1,3.0,2.701248,2.233749


- füge dem Dataframe `data_np` eine neue Column mit dem Namen `column_sum` hinzu
- Der Column `column_sum` soll die Summe pro row `mittels apply` übergeben werden

,column_int,column_int_1,column_float,mean_row,column_sum
0,4,NaN,7.107220,5.553610,16.660830
1,5,5.0,-34.254537,-8.084846,-32.339383
2,9,4.0,-41.623017,-9.541006,-38.164022
3,1,8.0,-11.140966,-0.713655,-2.854621
4,2,4.0,9.046414,5.015471,20.061885
...,...,...,...,...,...
95,8,1.0,39.788567,16.262856,65.051423
96,4,4.0,-83.671967,-25.223989,-100.895957
97,1,9.0,59.157147,23.052382,92.209530
98,1,3.0,2.701248,2.233749,8.934997


- füge dem Dataframes `data_np` eine neue row hinzu
- übergebe der neuen row die Summe pro Column mittels loc

,column_int,column_int_1,column_float,mean_row,column_sum
0,4.00,NaN,7.107220,5.553610,16.660830
1,5.00,5.0000,-34.254537,-8.084846,-32.339383
2,9.00,4.0000,-41.623017,-9.541006,-38.164022
3,1.00,8.0000,-11.140966,-0.713655,-2.854621
4,2.00,4.0000,9.046414,5.015471,20.061885
...,...,...,...,...,...
96,4.00,4.0000,-83.671967,-25.223989,-100.895957
97,1.00,9.0000,59.157147,23.052382,92.209530
98,1.00,3.0000,2.701248,2.233749,8.934997
99,9.00,3.0000,-59.428650,-15.809550,-63.238199


## Aufgabe 2: numpy Funktionen

### a) allgemeine Funktionen

- Was ist der cosinuns von 1?

0.5403023058681398

- erstelle ein Array mit 12 Elementen, welche alle den gleichen Wert haben z.B. 0
- unterteile das erstellte Array in `drei` unter Listen, welche jeweils aus `vier` Elementen besteht

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- erstelle nun ein Attay mit unterschiedlichen Zahlen, nachden gleichen Zahlen bereichen

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


### b) Slicing
- bilde ein 1-dimensionales Array aus 6 Zahlen (1,2, usw.) mit dem Namen `arr`

array([1, 2, 3, 4, 5, 6])

- verwende die Slicing-Notation um die `letzten 4 Elemente` aus dem Array `arr` anzuzeigen

array([3, 4, 5, 6])

- verwende die Slicing-Notation, sodass `jedes zweites Element` ab der `zweiten` Zahl bis zur `fünften` Zahl ausgegeben wird aus dem Array `arr` 

array([2, 4])

- bilde ein neues 2-dimensionales Array mit dem Namen `arr2` mit jeweils `drei` unter Listen, welche jeweils aus `vier` Elementen besteht
- [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


- verwende die Slicing-Notation, um aus dem Array `arr2` dir die aus der ersten Dimension, die ersten beiden Elementen anzuzeigen

array([1, 2])

- zeige aus dem Array `arr2` 
    - aus den beiden ersten Dimensionen (1. Dimension und 2. Dimension) 
    - jeweils das dritte Element an

array([3, 7])

- wähle aus dem Array `arr2` 
    - aus den beiden ersten Dimensionen 
    - jeweils das zweite Element und alle Elemente ab dem zweiten Element aus

array([[ 2,  4],
       [10, 12]])

### c) Weitere Aspekte
- itteriere über das Array `arr2` und gebe jedes Element **einzelend** aus
- mittels fo-loops

1
2
3
4
5
6
7
8
9
10
11
12


- verwende eine numpy funktion zum lösen 
<br><br> **Tipp** es geht Richtung `iter`

1
2
3
4
5
6
7
8
9
10
11
12


- bestimme mittels einer Standard Funktion in numpy den Datentyp des Arrays

dtype('int64')

- splitte das Array mittels einer Standard Funktion in numpy nachdem zweiten Element auf 

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

- bestimme die Position des Elements = 6 in dem Array mittels einer Standard Funktion in numpy
- where

(array([1]), array([1]))

- erstelle ein Array mittels einer Standard Funktion in numpy bei dem jedes `zweite Element` angezeigt wird beginnend bei `1` und endet bei `20`

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])